'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data, me, currentProject=localStorage.getItem('forge.project')||'', currentOrg='', view='dashboard', filter='open', search='', selected='', stream, modalHandler, repoPage=1, authMode='login';
const user=id=>data?.users.find(u=>u.id===id), userName=id=>user(id)?.name||id, initials=id=>userName(id).split(' ').map(n=>n[0]).join('').slice(0,2), avatar=id=>`<span class="avatar">${esc(initials(id))}</span>`;
const project=()=>data?.projects.find(p=>p.id===currentProject), org=()=>data?.organizations.find(o=>o.id===(project()?.org_id||currentOrg));
const list=key=>(data?.[key]||[]).filter(v=>v.project_id===currentProject), badge=s=>`<span class="badge ${esc(s)}">${s==='passed'?'✓ ':s==='running'?'◌ ':''}${esc(s)}</span>`, short=id=>String(id).length<8?id:String(id).slice(0,6);
const date=s=>s?new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'No date', age=s=>{const n=Math.max(0,Math.floor((Date.now()-new Date(s))/60000));return n<1?'just now':n<60?`${n}m ago`:n<1440?`${Math.floor(n/60)}h ago`:date(s)};
const ranks={guest:1,developer:2,maintainer:3,owner:4}, level=()=>Math.max(ranks[project()?.members?.[me]]||0,ranks[org()?.members?.[me]]||0);
const button=(text,action,cls='button',id='')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${text}</button>`;
function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500)}
async function api(path,body){const res=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Requested-With':'forge'}:{},body:body?JSON.stringify(body):undefined});const out=await res.json();if(!res.ok)throw Error(out.error||'Request failed');return out}
async function command(c){return api('action',{project_id:currentProject,...c})}
async function refresh(){const result=await api('state');data=result.data;me=result.user_id;if(!data.organizations.some(o=>o.id===currentOrg))currentOrg=data.organizations[0]?.id||'';if(!project())currentProject=data.projects.find(p=>p.org_id===currentOrg)?.id||'';if(project())currentOrg=project().org_id;render()}
function connect(){stream?.close();stream=new EventSource('/api/events');stream.addEventListener('ready',()=>{$('#live-dot').classList.add('connected');$('#live-label').textContent='Live updates connected'});stream.addEventListener('update',()=>refresh().catch(e=>toast(e.message)));stream.onerror=()=>{$('#live-dot').classList.remove('connected');$('#live-label').textContent='Reconnecting…'}}
async function init(){try{const s=await api('session');$('#demo-label').hidden=!s.demo;$('#demo-badge').hidden=!s.demo;if(!s.user_id){stream?.close();$('#login').hidden=false;$('#app').hidden=true;setAuthMode(location.pathname==='/signup'?'signup':'login');return}$('#login').hidden=true;$('#app').hidden=false;const q=new URLSearchParams(location.search);if(q.get('project'))currentProject=q.get('project');await refresh();connect();history.replaceState(null,'','/dashboard');if(q.get('review')){view='mrs';selected='';render()}else if(q.get('import'))await showImport(q.get('import'))}catch(e){toast(e.message)}}
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';$('#name-label').hidden=!signup;$('#name-label input').disabled=!signup;$('#name-label input').required=signup;$('#password-hint').hidden=!signup;const pass=$('#login-form [name=password]');pass.autocomplete=signup?'new-password':'current-password';pass.minLength=signup?12:1;$('#auth-title').textContent=signup?'Build something together.':'Welcome back.';$('#auth-description').textContent=signup?'Create your account and make room for your next great project.':'A shared place for your next great idea. Log in to pick up where you left off.';$('#auth-submit').textContent=signup?'Create account →':'Log in →';$('#auth-switch').innerHTML=signup?'Already have an account? <a href="/login" data-auth="login">Log in</a>':'New to Forge? <a href="/signup" data-auth="signup">Create an account</a>';$('#auth-error').textContent='';document.querySelectorAll('[data-auth]').forEach(a=>a.classList.toggle('active',a.dataset.auth===mode));history.replaceState(null,'',signup?'/signup':'/login')}
function passwordVisibility(visible){const input=$('#login-form [name=password]'),toggle=$('#password-toggle');input.type=visible?'text':'password';toggle.textContent=visible?'Hide password':'Show password';toggle.setAttribute('aria-pressed',String(visible))}
$('#password-toggle').addEventListener('click',()=>passwordVisibility($('#login-form [name=password]').type==='password'));
$('#login-form').addEventListener('reset',()=>passwordVisibility(false));
document.addEventListener('click',e=>{const link=e.target.closest('[data-auth]');if(link){e.preventDefault();passwordVisibility(false);setAuthMode(link.dataset.auth)}});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#auth-submit').disabled=true;$('#auth-error').textContent='';try{await api(authMode,Object.fromEntries(new FormData(e.target)));e.target.reset();view='dashboard';currentOrg='';currentProject='';await init()}catch(e){$('#auth-error').textContent=e.message}finally{$('#auth-submit').disabled=false}});
$('#demo-login').addEventListener('click',async()=>{try{await api('login',{user_id:$('#demo-user').value});view='dashboard';await init()}catch(e){$('#auth-error').textContent=e.message}});
const navItems=[['dashboard','◈','Dashboard'],['overview','◫','Project overview'],['issues','⊙','Issues'],['mrs','⑂','Merge requests'],['pipelines','▷','CI / Pipelines'],['milestones','⚑','Milestones'],['activity','◷','Activity'],['members','♧','Members & teams'],['audit','▤','Audit log'],['settings','⚙','Settings']];
function render(){const p=project();$('#org-select').innerHTML=data.organizations.map(o=>`<option value="${o.id}" ${o.id===currentOrg?'selected':''}>${esc(o.name)}</option>`).join('');$('#project-select').innerHTML=data.projects.filter(p=>p.org_id===currentOrg).map(p=>`<option value="${p.id}" ${p.id===currentProject?'selected':''}>${esc(p.name)}</option>`).join('')||'<option value="">No projects yet</option>';$('#project-select').disabled=!data.projects.some(p=>p.org_id===currentOrg);$('#nav').innerHTML=navItems.filter(([id])=>p||['dashboard','members'].includes(id)).map(([id,icon,name],i)=>`${i===7?'<div class="nav-divider"></div>':''}<button class="nav-item ${view===id?'active':''}" data-view="${id}"><span class="nav-icon">${icon}</span>${name}${id==='issues'||id==='mrs'?`<span class="nav-count">${list(id==='issues'?'issues':'merge_requests').filter(v=>v.state==='open').length}</span>`:''}</button>`).join('');$('#breadcrumb').innerHTML=`${esc(org()?.name||'Workspace')}<span class="slash">/</span><strong>${esc(view==='dashboard'?'Dashboard':p?.name||'Projects')}</strong>`;$('#profile').innerHTML=`${avatar(me)}<span>${esc(userName(me))}<small>Sign out ↗</small></span>`;$('#top-avatar').textContent=initials(me);$('#notification-count').textContent=data.notifications.filter(n=>!n.read).length||'';if(view==='dashboard'||(!p&&!['inbox','members'].includes(view))){$('#content').innerHTML=dashboard();return}const views={overview,issues,mrs:mergeRequests,pipelines,milestones,activity,members,audit,settings,inbox};$('#content').innerHTML=(views[view]||dashboard)();}
function heading(title,subtitle,actions=''){return `<div class="page-heading"><div><p class="eyebrow">${esc(project()?.name||'FORGE')} / ${esc(view.toUpperCase())}</p><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="actions">${actions}</div></div>`}
const empty=text=>`<div class="empty">${text}</div>`;
function dashboard(){
 const mine=data.issues.filter(i=>i.assignee_id===me&&i.state==='open');
 const reviews=data.merge_requests.filter(m=>m.state==='open'&&m.author_id!==me&&!m.approvals.includes(me));
 const running=data.pipelines.filter(p=>['queued','running'].includes(p.state));
 const stats=[['Projects',data.projects.length,'A shared place to build','◈'],['Assigned to you',mine.length,'Your next steps','⊙'],['Awaiting review',reviews.length,'Open conversations','⑂'],['Active pipelines',running.length,'Work in motion','▷']];
 const title=`Good to see you, ${userName(me).split(' ')[0]}.`;
 const projects=data.projects.length?`<div class="dashboard-projects">${data.projects.map(p=>`<button class="dashboard-project" data-action="open-project" data-id="${p.id}"><span class="project-avatar">◈</span><h3>${esc(p.name)}</h3><p>${esc(p.description||'A fresh space for your team’s next idea.')}</p><div class="project-meta"><span>⊙ ${data.issues.filter(i=>i.project_id===p.id&&i.state==='open').length} issues</span><span>⑂ ${data.merge_requests.filter(m=>m.project_id===p.id&&m.state==='open').length} requests</span><span>${p.archived?'Archived':'Open project →'}</span></div></button>`).join('')}</div>`:`<div class="dashboard-empty"><span class="mr-icon">◈</span><h2>Your first project starts here.</h2><p>Create a home for your code, turn ideas into issues, and bring your team along for the journey.</p>${button('＋ Create your first project','project','primary')}</div>`;
 const tasks=mine.slice(0,5).map(i=>`<div class="dashboard-task"><span class="issue-icon">⊙</span><div><p>${esc(i.title)}</p><small>${esc(data.projects.find(p=>p.id===i.project_id)?.name||'Project')}</small></div>${button('Open','dashboard-issue','button',i.id)}</div>`).join('')||empty('Nothing assigned to you. Room for your next good idea.');
 return heading('Your dashboard','Your projects, your people, and what’s next.',button('＋ New organization','organization')+button('＋ New project','project','primary'))+`<section class="dashboard-welcome"><div><h2>${esc(title)}</h2><p>${data.projects.length?'Everything you’re building, in one place. Let’s keep things moving.':'Your workspace is ready. Let’s turn the first idea into a project.'}</p></div><span class="big-symbol" aria-hidden="true">◈</span></section><div class="stats">${stats.map(([label,n,sub,icon])=>`<div class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><strong>${n}</strong><small>${sub}</small></div>`).join('')}</div><h2 class="section-title">Your projects</h2>${projects}<div class="columns"><div>${card('Your to-do list',tasks)}</div><div>${card('Across your workspace',feed(data.activity.slice(-5)))}</div></div>`;
}
function card(title,body,action=''){return `<section class="card"><div class="card-head"><h2>${title}</h2>${action}</div>${body}</section>`}
function issueRow(i){return `<div class="row clickable" data-action="issue-detail" data-id="${i.id}" tabindex="0" role="button"><span class="issue-icon">${i.state==='open'?'⊙':'✓'}</span><div class="row-main"><div class="row-title">${esc(i.title)}</div><div class="row-meta"><span>#${short(i.id)}</span>${(i.labels||[]).map(l=>`<span class="tag">${esc(data.labels.find(v=>v.id===l)?.name||l)}</span>`).join('')}<span>opened ${age(i.created_at)}</span></div></div>${i.assignee_id?avatar(i.assignee_id):''}</div>`}
function mrRow(m){return `<div class="row clickable" data-action="mr-detail" data-id="${m.id}" tabindex="0" role="button"><span class="mr-icon">⑂</span><div class="row-main"><div class="row-title">${esc(m.title)}</div><div class="row-meta">!${short(m.id)}<span class="branch">${esc(m.source)} → ${esc(m.target)}</span></div></div>${badge(m.state)}</div>`}
function pipelineRow(p){return `<div class="row clickable" data-action="pipeline-detail" data-id="${p.id}" tabindex="0" role="button">${badge(p.state)}<div class="row-main"><div class="row-title">${esc(p.ref)}</div><div class="row-meta">#${short(p.id)}<span>Simulation · ${age(p.created_at)}</span></div></div><span class="branch">↗</span></div>`}
function feed(events,showHash=false){return events.length?[...events].reverse().map(e=>`<div class="feed-row"><span class="feed-symbol">${e.action.includes('pipeline')?'▷':e.action.includes('mr')?'⑂':'◇'}</span><div class="feed-text"><strong>${esc(userName(e.actor_id))}</strong> · ${esc(e.action.replaceAll('.',' '))}<br>${esc(e.detail)}<small>${date(e.created_at)} · ${age(e.created_at)}</small>${showHash?`<div class="hash">SHA-256 ${esc(e.hash)}</div>`:''}</div></div>`).join(''):empty('A fresh start. Activity will appear as your team works.')}
function overview(){const p=project(),open=list('issues').filter(i=>i.state==='open'),mrs=list('merge_requests').filter(i=>i.state==='open'),pipes=list('pipelines'),passed=pipes.filter(i=>i.state==='passed').length;return heading('Project overview','A little context. A clear path forward.',button('↗ Import repository','import')+button('＋ New issue','issue','primary'))+`<section class="hero"><div><p class="eyebrow">LET’S BUILD SOMETHING GREAT</p><h2>Everything in sync. Your team in flow.</h2><p>${esc(p.description||'Bring your code, conversations, and delivery together in one place.')}</p></div><div class="hero-art" aria-hidden="true">〈 / 〉</div></section><div class="stats">${[['Open issues',open.length,'Ready for the next step','⊙'],['Merge requests',mrs.length,'Good ideas, in review','⑂'],['Pipeline pass rate',pipes.length?Math.round(passed/pipes.length*100)+'%':'—','Simulated CI runs','▷'],['Contributors',data.users.filter(u=>Math.max(ranks[p.members[u.id]]||0,ranks[org()?.members[u.id]]||0)>0).length,'Building better, together','♧']].map(([label,note,sub,icon])=>`<div class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><strong>${note}</strong><small>${sub}</small></div>`).join('')}</div><div class="columns"><div>${card('On your radar <span class="count-pill">'+open.length+'</span>',open.slice(0,4).map(issueRow).join('')||empty('All clear. Create an issue to plan your next step.'),'<button class="text-button" data-view="issues">View all →</button>')}${card('Merge requests',mrs.slice(0,3).map(mrRow).join('')||empty('No open merge requests.'),'<button class="text-button" data-view="mrs">View all →</button>')}${card('Latest pipelines',[...pipes].reverse().slice(0,2).map(pipelineRow).join('')||empty('Run your first pipeline.'),'<button class="text-button" data-view="pipelines">View all →</button>')}</div><div>${card('Repository',`<div class="repo-details"><p><span>◈ Repository</span><strong>${esc(p.repository.full_name||p.name)}</strong></p><p><span>⑂ Default branch</span><strong>${esc(p.repository.default_branch||'main')}</strong></p><p><span>◇ Provider</span><strong>${esc(p.repository.provider)}</strong></p><p><span>♧ Team</span><strong>${esc(data.teams.find(t=>t.id===p.team_id)?.name||'Unassigned')}</strong></p><p><span>✓ Required approvals</span><strong>${p.required_approvals}</strong></p></div>`)}${card('Recent activity',feed(list('activity').slice(-4)),'<button class="text-button" data-view="activity">View all →</button>')}<div class="note"><strong>A home for your next release.</strong><br>Keep work focused with labels, milestones, and a shared view of what comes next.</div></div></div>`}
function toolbar(states){return `<div class="toolbar" role="group" aria-label="${view==='issues'?'Issue':'Merge request'} search and status filters">${states.map(s=>`<button class="tab ${filter===s?'active':''}" data-filter="${s}" aria-pressed="${filter===s}">${s[0].toUpperCase()+s.slice(1)}</button>`).join('')}<input id="search" aria-label="${view==='issues'?'Search issues':'Search merge requests'}" aria-keyshortcuts="/" title="Press / to focus search" placeholder="${view==='issues'?'Search title, description, or ID…':'Search title, description, branch, or ID…'}" value="${esc(search)}">${search?button('Clear search','clear-search'):''}</div>`}
const issueFilters = new Map();
function issuePreferences(){if(!issueFilters.has(currentProject))issueFilters.set(currentProject,{assignee:'',label:'',milestone:'',sort:'newest'});return issueFilters.get(currentProject)}
function filteredIssues(){
 const prefs=issuePreferences(), query=search.trim().toLowerCase();
 const items=list('issues').filter(i=>(filter==='all'||i.state===filter)&&
  (!query||`${i.title} ${i.body||''} ${i.id}`.toLowerCase().includes(query))&&
  (!prefs.assignee||(prefs.assignee==='unassigned'?!i.assignee_id:i.assignee_id===(prefs.assignee==='me'?me:prefs.assignee)))&&
  (!prefs.label||(i.labels||[]).includes(prefs.label))&&
  (!prefs.milestone||(prefs.milestone==='none'?!i.milestone_id:i.milestone_id===prefs.milestone)));
 return items.sort((a,b)=>prefs.sort==='title'?a.title.localeCompare(b.title):prefs.sort==='oldest'?String(a.created_at).localeCompare(String(b.created_at)):String(b.created_at).localeCompare(String(a.created_at)));
}
function issues(){
 const prefs=issuePreferences(), items=filteredIssues();
 const control=(label,key,choices)=>`<label>${label}<select data-issue-filter="${key}">${choices.map(([value,text])=>`<option value="${esc(value)}" ${prefs[key]===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
 return heading('Issues','Find the work that needs your attention.',button('＋ Label','label')+button('＋ New issue','issue','primary'))+toolbar(['open','closed','all'])+
 `<div class="issue-filters">${control('Assignee','assignee',[['','Anyone'],['me','Assigned to me'],['unassigned','Unassigned'],...data.users.map(u=>[u.id,u.name])])}${control('Label','label',[['','Any label'],...list('labels').map(l=>[l.id,l.name])])}${control('Milestone','milestone',[['','Any milestone'],['none','No milestone'],...list('milestones').map(m=>[m.id,m.title])])}${control('Sort by','sort',[['newest','Newest first'],['oldest','Oldest first'],['title','Title A–Z']])}${button('Clear filters','clear-issue-filters')}</div><p class="issue-results" role="status">${items.length} of ${list('issues').length} issues · Search matches title, description, or ID</p><div class="card">${items.map(issueRow).join('')||empty('No issues match these filters. Clear filters to see more work.')}</div>`;
}
function mergeRequests(){
 if(selected){const m=list('merge_requests').find(v=>v.id===selected);if(m)return mrDetail(m)}
 const query=search.trim().toLowerCase(), requests=list('merge_requests');
 const visible=requests.filter(i=>(filter==='all'||i.state===filter)&&(!query||[i.title,i.body,i.source,i.target,i.id,i.remote?.number].filter(v=>v!=null).join(' ').toLowerCase().includes(query)));
 return heading('Merge requests','Better code starts with a conversation.',(project().repository.provider!=='local'?button('Link provider request','remote-link','primary'):button('＋ New merge request','mr','primary')))+toolbar(['open','merged','closed','all'])+
 `<p class="issue-results" role="status">${visible.length} of ${requests.length} merge requests</p><div class="card">${visible.map(mrRow).join('')||empty(requests.length?'No matching merge requests. Try another search or choose All.':'No merge requests yet. Create or link a request to start a review.')}</div>`;
}
function mrDetail(m){if(m.remote)return remoteDetail(m);const p=project(),valid=m.approvals.filter(uid=>uid!==m.author_id&&Math.max(ranks[p.members[uid]]||0,ranks[org()?.members[uid]]||0)>=2);return heading(m.title,`${m.source} → ${m.target}`,button('← All requests','back'))+`<div class="note">${badge(m.state)} &nbsp; ${valid.length} / ${p.required_approvals} required approvals · ${p.require_pipeline?'Passing pipeline required':'Pipeline optional'} · Metadata merge only; the remote repository is unchanged.</div>`+card(`!${short(m.id)} · ${esc(userName(m.author_id))}`,`<div class="detail-body">${esc(m.body||'No description provided.')}</div>${m.state==='open'?`<div class="detail-actions">${button('✓ Approve','approve','button',m.id)}${button('＋ Review comment','comment','button',m.id)}${button('▷ Run pipeline','mr-pipeline','button',m.id)}${button('Merge request','merge','primary',m.id)}${button('Close','close-mr','button danger',m.id)}</div>`:''}`)+card('Review discussions',m.comments.map(c=>`<div class="row"><div class="row-main"><div class="row-title">${esc(userName(c.author_id))} ${c.resolved?badge('closed'):''}</div>${c.path?`<div class="row-meta">${esc(c.path)}:${c.line||'file'}</div>`:''}<div class="detail-body">${esc(c.body)}</div></div>${!c.resolved&&m.state==='open'?`<button class="button" data-action="resolve" data-id="${m.id}" data-comment="${c.id}">Resolve</button>`:''}</div>`).join('')||empty('No review comments yet.'))+card('Pipelines',list('pipelines').filter(v=>v.mr_id===m.id).reverse().map(pipelineRow).join('')||empty('No pipelines for this request.'))}
let pipelineFilter='all';
function pipelines(){
 const runs=[...list('pipelines')].reverse(), states=['all','queued','running','passed','failed'];
 const visible=runs.filter(p=>pipelineFilter==='all'||p.state===pipelineFilter);
 return heading('CI / Pipelines','A clear view from queued to complete.',button('▷ Run pipeline','pipeline','primary'))+`<div class="note"><strong>Simulation mode</strong> · Runs advance through queued → running → passed / failed. No code or shell commands are executed.</div>`+
 `<div class="toolbar" role="group" aria-label="Pipeline status filters">${states.map(state=>`<button class="tab ${pipelineFilter===state?'active':''}" data-action="pipeline-filter" data-id="${state}" aria-pressed="${pipelineFilter===state}">${state[0].toUpperCase()+state.slice(1)} (${state==='all'?runs.length:runs.filter(p=>p.state===state).length})</button>`).join('')}</div><div class="card">${visible.map(p=>pipelineRow(p)+(selected===p.id?`<div class="detail-actions">${button('Copy logs','copy-pipeline-logs','button',p.id)}${button('Download logs','download-pipeline-logs','button',p.id)}</div><pre class="log">${esc(p.logs.join('\n'))}</pre>`:'')).join('')||empty(runs.length?'No pipelines match this status. Choose All to see every run.':'No pipelines yet. Start your first simulation.')}</div>`;
}
let milestoneFilter='all';
function milestones(){
 const items=list('milestones'), visible=items.filter(m=>milestoneFilter==='all'||m.state===milestoneFilter);
 const tabs=`<div class="toolbar" role="group" aria-label="Milestone status filters">${['all','open','closed'].map(state=>`<button class="tab ${milestoneFilter===state?'active':''}" data-action="milestone-filter" data-id="${state}" aria-pressed="${milestoneFilter===state}">${state[0].toUpperCase()+state.slice(1)} (${state==='all'?items.length:items.filter(m=>m.state===state).length})</button>`).join('')}</div>`;
 return heading('Milestones','Give the next chapter a finish line.',button('＋ New milestone','milestone','primary'))+tabs+(visible.map(m=>{const issues=list('issues').filter(i=>i.milestone_id===m.id),done=issues.filter(i=>i.state==='closed').length;return card(esc(m.title),`<div class="repo-details"><p><span>Due ${esc(m.due_date||'anytime')}</span>${badge(m.state)}</p><progress class="progress" value="${done}" max="${issues.length||1}" aria-label="Milestone progress"></progress><p><span>${done} of ${issues.length} issues completed</span>${button('View issues','milestone-issues','button',m.id)}${button(m.state==='open'?'Close milestone':'Reopen milestone','milestone-state','button',m.id)}</p></div>`) }).join('')||empty(items.length?'No milestones match this status. Choose All to see every milestone.':'No milestones yet. Create one to plan your next release.'));
}
function activity(){return heading('Activity','The story of your project, one update at a time.')+`<div class="note">Append-only activity. Events are hash-linked and verified when the server starts.</div>`+`<div class="card">${feed(list('activity'))}</div>`}
function audit(){return heading('Audit log','Accountability for the actions that matter.')+`<div class="note">${level()<3?'Audit records are visible to maintainers and owners.':'Sensitive project and organization actions are recorded in a separate append-only, hash-linked log.'}</div><div class="card">${feed(data.audit.filter(e=>e.project_id===currentProject||(!e.project_id&&e.org_id===currentOrg)),true)}</div>`}
function members(){
 const o=org(),p=project(),orgLevel=ranks[o?.members?.[me]]||0;
 const canManageTeams=orgLevel>=3,canManageRoles=orgLevel>=4||(p&&level()>=3);
 const actions=(canManageTeams?button('＋ Team','team'):'')+(canManageRoles?button('Manage roles','member','primary'):'');
 const people=data.users.filter(u=>o?.members?.[u.id]||p?.members?.[u.id]);
 const teams=data.teams.filter(t=>t.org_id===currentOrg);
 return heading('People & teams',o?`${o.name} · Shared ownership. Clear responsibilities.`:'Choose a workspace to view its teams.',actions)+
 `<div class="member-grid">${people.map(u=>`<div class="member-card">${avatar(u.id)}<h3>${esc(u.name)}</h3><p>${esc(o?.members?.[u.id]||'Project member')} · ${esc(o?.name||'External')}</p>${badge(Object.entries(ranks).find(([,n])=>n===Math.max(ranks[p?.members?.[u.id]]||0,ranks[o?.members?.[u.id]]||0))?.[0]||'guest')}</div>`).join('')}</div>`+
 `<h2 class="section-title">Organization teams <span class="count-pill">${teams.length}</span></h2><div class="card">${teams.map(t=>`<div class="row"><span class="mr-icon">♧</span><div class="row-main"><div class="row-title">${esc(t.name)}</div><div class="row-meta">${t.members.length?t.members.map(userName).map(esc).join(', '):'No members yet'}</div></div>${p&&t.id===p.team_id?badge('assigned'):''}${canManageTeams?button('Edit','team-edit','button',t.id):''}</div>`).join('')||empty(canManageTeams?'No teams yet. Create a team to organize contributors.':'No teams in this workspace yet.')}</div>`+
 `<div class="note">Teams belong to your workspace and can be created before a project. Organization roles are inherited by projects. Assign a team to a project in Project settings.</div>`;
}
function settings(){const p=project();return heading('Project settings','A few thoughtful defaults go a long way.',button('＋ New project','project'))+`<div class="settings-grid"><section class="card"><h2>General & merge rules</h2><form id="settings-form"><label>Project name<input name="name" required value="${esc(p.name)}"></label><label>Description<textarea name="description">${esc(p.description)}</textarea></label><label>Team<select name="team_id">${teamOptions(p.team_id)}</select></label><label>Required approvals<input type="number" name="required_approvals" min="0" max="10" value="${p.required_approvals}" required></label><label class="check"><input type="checkbox" name="require_pipeline" ${p.require_pipeline?'checked':''}>Require a passing pipeline before merge</label><label class="check"><input type="checkbox" name="archived" ${p.archived?'checked':''}>Archive project (read-only)</label><button class="primary">Save settings</button></form></section><div>${card('Repository connection',`<div class="repo-details"><p>${esc(p.repository.full_name||'No repository imported')}</p><p>${esc(p.repository.provider)} · ${esc(p.repository.default_branch||'main')}</p>${button('Connect & import','import')}</div>`)}${card('Webhook ingestion',`<div class="repo-details"><p>GitHub endpoint</p><div class="code">${esc(location.origin)}/api/webhooks/github/${p.id}</div><p>GitLab endpoint</p><div class="code">${esc(location.origin)}/api/webhooks/gitlab/${p.id}</div><p>Shared secret</p><div class="code">${esc(p.webhook_secret||'Maintainer access required')}</div><br>${button('Rotate secret','rotate')}</div>`)}<div class="note">GitHub payloads require a SHA-256 signature. GitLab requests require the secret token. Delivery IDs prevent duplicate events.</div></div></div>`}
let unreadOnly=false;
function inbox(){
 const unread=data.notifications.filter(n=>!n.read).length;
 const notifications=[...data.notifications].reverse().filter(n=>!unreadOnly||!n.read);
 return heading('Notifications',`${unread} unread notification${unread===1?'':'s'}.`,unread?button('Mark all read','read-notifications'):'')+
 `<div class="toolbar" role="group" aria-label="Notification filters"><button class="tab ${!unreadOnly?'active':''}" data-action="notification-filter" data-id="all" aria-pressed="${!unreadOnly}">All (${data.notifications.length})</button><button class="tab ${unreadOnly?'active':''}" data-action="notification-filter" data-id="unread" aria-pressed="${unreadOnly}">Unread (${unread})</button></div><div class="card">${notifications.map(n=>`<div class="row"><span class="feed-symbol" aria-label="${n.read?'Read':'Unread'}">${n.read?'✓':'●'}</span><div class="row-main"><div class="row-title">${esc(n.message)}</div><div class="row-meta">${age(n.created_at)}</div></div>${n.read?'':button('Mark read','read-notification','button',n.id)}</div>`).join('')||empty(unreadOnly?'You’re all caught up. No unread notifications.':'No notifications yet.')}</div>`;
}
function field(label,name,value='',type='text',required=true){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`}
function options(items,value,blank='None'){return `<option value="">${blank}</option>`+items.map(([id,name])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(name)}</option>`).join('')}
function teamOptions(value){return options(data.teams.filter(t=>t.org_id===currentOrg).map(t=>[t.id,t.name]),value)}
function modal(title,body,submit,handler){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal-submit').textContent=submit;$('#modal-submit').hidden=!handler;$('#form-error').textContent='';modalHandler=handler;$('#modal').showModal()}
function issueModal(id){const i=list('issues').find(i=>i.id===id);modal(i?'Edit issue':'New issue',field('Title','title',i?.title)+`<label>Description<textarea name="body">${esc(i?.body||'')}</textarea></label><div class="field-row"><label>Assignee<select name="assignee_id">${options(data.users.map(u=>[u.id,u.name]),i?.assignee_id,'Unassigned')}</select></label><label>Milestone<select name="milestone_id">${options(list('milestones').map(m=>[m.id,m.title]),i?.milestone_id)}</select></label></div><label>Labels<select name="labels" multiple>${list('labels').map(l=>`<option value="${l.id}" ${i?.labels?.includes(l.id)?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label>${i?`<label>Status<select name="state"><option ${i.state==='open'?'selected':''}>open</option><option ${i.state==='closed'?'selected':''}>closed</option></select></label>`:''}`,i?'Save changes':'Create issue',async(f,form)=>command({kind:i?'issue.update':'issue.create',id:i?.id||'',...f,labels:[...form.elements.labels.selectedOptions].map(o=>o.value)}))}
function pipelineModal(mrid=''){const m=list('merge_requests').find(v=>v.id===mrid);modal('Run a simulated pipeline',`<div class="note">A simulated runner produces logs and a deterministic outcome in about six seconds.</div>`+field('Branch / ref','ref',m?.source||project().repository.default_branch||'main')+`<label>Merge request<select name="mr_id">${options(list('merge_requests').filter(m=>m.state==='open').map(m=>[m.id,m.title]),mrid,'Standalone pipeline')}</select></label><label>Simulation outcome<select name="outcome"><option value="passed">Passed</option><option value="failed">Failed</option></select></label>`,'Run pipeline',async f=>command({kind:'pipeline.create',...f}))}
async function showImport(providerName){if(!providerName){modal('Import repository',`<div class="note">Connect your account, then select a repository to import its metadata. Your code stays with the provider.</div><a class="button" href="/api/oauth/github/start?project_id=${currentProject}">Connect GitHub ↗</a> <a class="button" href="/api/oauth/gitlab/start?project_id=${currentProject}">Connect GitLab ↗</a><p class="note">Requires provider OAuth credentials configured on the server.</p>`,'',null);return}const result=await api(`oauth/${providerName}/repositories?page=${repoPage}`);modal('Choose a repository',result.repositories.map(r=>`<div class="import-row"><span>${esc(r.full_name)}</span><button type="button" class="button" data-action="import-repo" data-provider="${providerName}" data-id="${r.external_id}">Import</button></div>`).join('')+`<div class="detail-actions">${repoPage>1?`<button type="button" class="button" data-action="repo-prev" data-provider="${providerName}">Previous</button>`:''}${result.has_more?`<button type="button" class="button" data-action="repo-next" data-provider="${providerName}">Next</button>`:''}</div>`,'',null)}
function teamModal(id){const t=data.teams.find(t=>t.id===id);modal(t?'Edit team':'New team',field('Team name','name',t?.name)+`<label>Members <span class="field-hint">Select the people to include in this team.</span><select name="members" multiple size="5">${data.users.filter(u=>org()?.members[u.id]).map(u=>`<option value="${u.id}" ${t?.members.includes(u.id)?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label>`,t?'Save changes':'Create team',(f,form)=>command({kind:t?'team.update':'team.create',id:t?.id||'',org_id:currentOrg,...f,members:[...form.elements.members.selectedOptions].map(o=>o.value)}))}
$('#modal-form').addEventListener('submit',async e=>{e.preventDefault();if(!modalHandler)return;$('#modal-submit').disabled=true;try{await modalHandler(Object.fromEntries(new FormData(e.target)),e.target);$('#modal').close();await refresh();toast('Saved successfully')}catch(e){$('#form-error').textContent=e.message}finally{$('#modal-submit').disabled=false}});
document.addEventListener('submit',async e=>{if(e.target.id!=='settings-form')return;e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await command({kind:'project.settings',...f,required_approvals:Number(f.required_approvals),require_pipeline:e.target.elements.require_pipeline.checked,archived:e.target.elements.archived.checked});await refresh();toast('Project settings saved')}catch(e){toast(e.message)}});
$('#project-select').addEventListener('change',e=>{currentProject=e.target.value;localStorage.setItem('forge.project',currentProject);selected='';render()});$('#org-select').addEventListener('change',e=>{currentOrg=e.target.value;currentProject=data.projects.find(p=>p.org_id===currentOrg)?.id||'';selected='';render()});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;search=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{if(e.target.name==='mr_id'&&e.target.value){const m=list('merge_requests').find(m=>m.id===e.target.value);e.target.form.elements.ref.value=m.source}});
document.addEventListener('change',e=>{const key=e.target.dataset?.issueFilter;if(['assignee','label','milestone','sort'].includes(key)){issuePreferences()[key]=e.target.value;render()}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.clickable')){e.preventDefault();e.target.click()}});
document.addEventListener('keydown',e=>{
 if(e.defaultPrevented||e.isComposing||e.ctrlKey||e.metaKey||e.altKey||e.shiftKey)return;
 if(e.key==='Escape'&&e.target.id==='search'&&e.target.value&&!document.querySelector('dialog[open]')){
  e.preventDefault();search='';render();$('#search')?.focus();return;
 }
 if(e.key!=='/')return;
 if(e.target.closest('input,textarea,select,[role="textbox"],[role="combobox"],[role="listbox"]')||e.target.isContentEditable||document.querySelector('dialog[open]'))return;
 const input=$('#search');
 if(!input||input.disabled||!input.getClientRects().length)return;
 e.preventDefault();input.focus();input.select();
});
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav){view=nav.dataset.view;selected='';filter='open';search='';render();return}const tab=e.target.closest('[data-filter]');if(tab){filter=tab.dataset.filter;render();document.querySelector(`[data-filter="${filter}"]`)?.focus();return}const b=e.target.closest('[data-action]');if(!b)return;const {action,id,provider}=b.dataset;try{switch(action){
case 'close-modal':$('#modal').close();return;
case 'clear-issue-filters':issueFilters.delete(currentProject);filter='all';search='';render();return;
case 'clear-search':search='';render();$('#search')?.focus();return;
case 'milestone-issues':issueFilters.set(currentProject,{assignee:'',label:'',milestone:id,sort:'newest'});view='issues';filter='all';search='';selected='';render();return;
case 'milestone-filter':if(!['all','open','closed'].includes(id))return;milestoneFilter=id;render();return;
case 'open-project':currentProject=id;currentOrg=project()?.org_id||currentOrg;localStorage.setItem('forge.project',id);view='overview';selected='';render();return;
case 'dashboard-issue':currentProject=data.issues.find(i=>i.id===id).project_id;currentOrg=project().org_id;issueModal(id);return;
case 'logout':await api('logout',{});stream?.close();await init();return;
case 'issue':issueModal();return;
case 'issue-detail':issueModal(id);return;
case 'mr-detail':view='mrs';selected=id;render();return;
case 'pipeline-detail':if(view!=='pipelines')pipelineFilter='all';view='pipelines';selected=selected===id?'':id;render();return;
case 'pipeline-filter':if(!['all','queued','running','passed','failed'].includes(id))return;pipelineFilter=id;selected='';render();return;
case 'copy-pipeline-logs':{
 const run=list('pipelines').find(p=>p.id===id);
 if(!run)throw Error('This pipeline is no longer available.');
 if(!run.logs?.length){toast('No logs to copy yet.');return}
 if(!navigator.clipboard?.writeText){toast('Clipboard is unavailable. Select the log text to copy it.');return}
 try{await navigator.clipboard.writeText(run.logs.join('\n'));toast('Pipeline logs copied.')}catch{toast('Clipboard access was denied. Select the log text to copy it.')}
 return;
}
case 'download-pipeline-logs':{
 const run=list('pipelines').find(p=>p.id===id);
 if(!run)throw Error('This pipeline is no longer available.');
 if(!run.logs?.length){toast('No logs to download yet.');return}
 const url=URL.createObjectURL(new Blob([run.logs.join('\n')+'\n'],{type:'text/plain;charset=utf-8'}));
 const link=document.createElement('a');
 link.href=url;link.download=`forge-pipeline-${String(run.id).replace(/[^a-zA-Z0-9_-]/g,'_')}.log`;
 try{document.body.appendChild(link);link.click();toast('Log download started.')}finally{link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return;
}
case 'back':selected='';render();return;
case 'inbox':view='inbox';render();return;
case 'notification-filter':unreadOnly=id==='unread';render();return;
case 'organization':modal('New organization',field('Organization name','name'),'Create organization',async f=>{const o=await command({kind:'organization.create',...f});currentOrg=o.id;currentProject=''});return;
case 'project':modal('New project',field('Project name','name')+`<label>Description<textarea name="description"></textarea></label><label>Organization<select name="org_id">${data.organizations.map(o=>`<option value="${o.id}" ${o.id===currentOrg?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label>`,'Create project',async f=>{const p=await command({kind:'project.create',...f});currentProject=p.id;currentOrg=p.org_id;view='overview'});return;
case 'team':teamModal();return;
case 'team-edit':teamModal(id);return;
case 'member':modal('Manage access',`<label>User<select name="user_id">${data.users.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label><label>Scope<select name="kind">${project()&&level()>=3?'<option value="project.member">Project</option>':''}${org()?.members?.[me]==='owner'?'<option value="organization.member">Organization</option>':''}</select></label><label>Role<select name="role"><option>guest</option><option>developer</option><option>maintainer</option><option>owner</option></select></label><div class="note">Organization access is inherited. Project roles grant additional access. Owner is an organization role.</div>`,'Save role',f=>command({...f,org_id:currentOrg}));return;
case 'label':modal('New label',field('Name','name')+field('Color','color','#8b6fca','color'),'Create label',f=>command({kind:'label.create',...f}));return;
case 'milestone':modal('New milestone',field('Title','title')+field('Due date','due_date','','date',false),'Create milestone',f=>command({kind:'milestone.create',...f}));return;
case 'milestone-state':await command({kind:'milestone.state',id,state:list('milestones').find(m=>m.id===id).state==='open'?'closed':'open'});break;
case 'mr':modal('New merge request',field('Title','title')+`<label>Description<textarea name="body"></textarea></label><div class="field-row">${field('Source branch','source')}${field('Target branch','target',project().repository.default_branch||'main')}</div>`,'Create merge request',async f=>{const m=await command({kind:'mr.create',...f});view='mrs';selected=m.id});return;
case 'comment':modal('Add review comment',`<label>Comment<textarea name="body" required></textarea></label><div class="field-row">${field('File path (optional)','path','','text',false)}${field('Line (optional)','line','0','number',false)}</div>`,'Add comment',f=>command({kind:'mr.comment',id,...f,line:Number(f.line)}));return;
case 'resolve':await command({kind:'mr.resolve',id,comment_id:b.dataset.comment});break;
case 'approve':await command({kind:'mr.approve',id});break;
case 'merge':await command({kind:'mr.merge',id});break;
case 'close-mr':await command({kind:'mr.close',id});break;
case 'pipeline':pipelineModal();return;
case 'mr-pipeline':pipelineModal(id);return;
case 'import':repoPage=1;await showImport();return;
case 'repo-prev':repoPage--;await showImport(provider);return;
case 'repo-next':repoPage++;await showImport(provider);return;
case 'import-repo':await api('import',{project_id:currentProject,provider,external_id:id});$('#modal').close();break;
case 'rotate':await command({kind:'webhook.rotate'});break;
case 'read-notifications':await command({kind:'notification.read'});break;
case 'read-notification':await command({kind:'notification.read',id});break;
default:return;
}await refresh();toast('Saved successfully')}catch(e){toast(e.message)}});
init();

